### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by mufeedcm** [bbkx226/terminalWebsite#2]
if we leave the website to another tab and come back the site crashes 😄

**Comment by bbkx226** [comment]
Are you having the issue that typing words doesn't function when you switch tabs back to the terminal website? In that situation, you'll need to click on the area where your typed word should appear. 
This is due to the code snippet in the file main.js, where it will auto-focus to the textarea in HTML the first time you run the website. But, if you click your cursor elsewhere, it will lose the focus, results in the issue I mentioned just now.
```
setTimeout(function() {
  loopLines(banner, "", 80);
  loopLines(suggestion, "", 2500);
  textarea.focus(); 
  // It's used to set focus on a textarea element in HTML. 
  // When an element has focus, it is ready to receive input from the user
}, 100);
```
However, if this isn't the case, could you please provide more information about the problem?

**Comment by mufeedcm** [comment]
thanks for replying :)
